apiVersion: v1
kind: Secret
metadata:
  name: inamute-app-secrets
  namespace: inamute
type: Opaque
stringData:
  DATABASE_URL: "postgresql://inamute:inamute_s3cur3_p%40ss_2024@inamute-db-rw.cnpg-databases.svc.cluster.local:5432/inamute"
  BETTER_AUTH_SECRET: "replace-with-a-32-byte-random-secret"
  API_KEY_HASH_SECRET: "replace-with-a-different-32-byte-random-secret"
  BETTER_AUTH_URL: "https://inamute.mris.dev"
  GOOGLE_CLIENT_ID: "replace-with-google-client-id"
  GOOGLE_CLIENT_SECRET: "replace-with-google-client-secret"
